baseURL = 'http://ernestphillips.dev/'
languageCode = 'en-us'
title = 'Ern Gets Good'
theme = "hugo-swift-theme"

[params]
  author = "Ernest Phillips"
  description = "Getting good at stuff."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/ernest-phillips"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/ErnGetsGood"